USE [master]
GO
-- CREATE AVAILABILITY GROUP W/REPLICAS & ENDPOINTS
CREATE AVAILABILITY GROUP [availgroup01]
WITH (
	AUTOMATED_BACKUP_PREFERENCE = SECONDARY,
	DB_FAILOVER = ON,
	DTC_SUPPORT = NONE,
	REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 0
)
FOR DATABASE [northwind]
REPLICA ON 
N'win25-db01' WITH (ENDPOINT_URL = N'TCP://win25-db01.sqldemo.local:5022', FAILOVER_MODE = AUTOMATIC, AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, BACKUP_PRIORITY = 50, SEEDING_MODE = AUTOMATIC, SECONDARY_ROLE(ALLOW_CONNECTIONS = ALL)),
N'win25-db02' WITH (ENDPOINT_URL = N'TCP://win25-db02.sqldemo.local:5022', FAILOVER_MODE = AUTOMATIC, AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, BACKUP_PRIORITY = 50, SEEDING_MODE = AUTOMATIC, SECONDARY_ROLE(ALLOW_CONNECTIONS = ALL)),
N'win25-db03' WITH (ENDPOINT_URL = N'TCP://win25-db03.sqldemo.local:5022', FAILOVER_MODE = MANUAL, AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT, BACKUP_PRIORITY = 50, SEEDING_MODE = AUTOMATIC, SECONDARY_ROLE(ALLOW_CONNECTIONS = NO));
GO

-- CREATE LISTENER
ALTER AVAILABILITY GROUP [availgroup01]
ADD LISTENER N'dblistener01' 
(
	WITH IP ((N'10.10.10.144', N'255.255.255.0'), (N'10.20.20.144', N'255.255.255.0')) , PORT=1433
);
GO
